// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1477.Robot.subsystems;

import org.usfirst.frc1477.Robot.RobotMap;
import org.usfirst.frc1477.Robot.commands.MoveArm;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Arm extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid gripSolenoid = RobotMap.armGripSolenoid;
    private final Encoder armEncoder = RobotMap.armArmEncoder;
    private final Encoder armRotatorEncoder = RobotMap.armArmRotatorEncoder;
    private final SpeedController armRotator = RobotMap.armArmRotator;
    private final SpeedController downMotor = RobotMap.armDownMotor;
    private final SpeedController upMotor = RobotMap.armUpMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private int Arm_Encoder_Value;
    private double Arm_Encoder_Rate;
    private int Rotator_Encoder_Value;
    private double Rotator_Encoder_Rate;
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new MoveArm(0));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
    	Arm_Encoder_Value = armEncoder.get();
    	Arm_Encoder_Rate = armEncoder.getRate();
    	Rotator_Encoder_Value = armRotatorEncoder.get();
    	Rotator_Encoder_Rate = armRotatorEncoder.getRate();
    }
    public void grabAndRelease() {
    	if (gripSolenoid.get() == Value.kForward)
    		gripSolenoid.set(Value.kReverse);
    	else
    		gripSolenoid.set(Value.kForward);
    }
    public void shiftArmUp() {
    	upMotor.set(.5);
    	downMotor.set(.5);
    }
    public void shiftArmDown() {
    	upMotor.set(-.5);
    	downMotor.set(-.5);
    }
    public void rotateArm() {
    	if (armRotator.get() > 0) {
    		armRotator.set(.5);
    	}
    	else if (armRotator.get() < 0) {
    		armRotator.set(-.5);
    	}
    }
    public void stopArmRotation() {
    	armRotator.set(0);
    }
    public void stopArmShift() {
    	upMotor.set(0);
    	downMotor.set(0);
    }
    public void stop() {
    	stopArmRotation();
    	stopArmShift();
    	gripSolenoid.set(Value.kOff);
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

